spring:
  profiles:
    active:
      - development
  datasource:
    url: jdbc:h2:mem:moviebookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none   # IMPORTANT: let Flyway manage schema
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: jdbc:h2:mem:moviebookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - caches
          - metrics
          - h2-console
logging:
  level:
    org:
      flywaydb: DEBUG
